## Importing Numpy

In [2]:
import numpy as np

### Numpy Arrays

#Vectors: 1-D arrays
#Matrices: 2-D arrays


Why use numpy arrays when you have list:

* 1. Memory efficient
* 2. Easily expandable to N-dimensions
* 3. Speed of calculations is higher in numpy array
* 4. Broadcasting operations and functions with numpy
* 5. All the data science libraries are built on top on Numpy

In [3]:
lst = [1,2,3]
arr = np.array(lst)

In [4]:
type(lst)

list

In [5]:
type(arr)

numpy.ndarray

In [6]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods to create arrays

In [8]:
#arange
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
#zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#ones
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
#linspace
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Random

In [14]:
#rand: crates an array of the given shape and populates it with random samples from a uniform distribution over [0,1)

In [20]:
np.random.rand(20)

array([0.42792076, 0.12326408, 0.17901345, 0.6750541 , 0.69200237,
       0.18515375, 0.14719862, 0.71060368, 0.73600795, 0.76571704,
       0.18074404, 0.38654653, 0.24290321, 0.35861829, 0.09931169,
       0.49206657, 0.60534784, 0.10710597, 0.78867088, 0.602005  ])

In [21]:
#randn: returns a sample from the 'standard normal' distribution. 
#Unlike rand which is uniform, values closer to zero are like to appear

np.random.randn(5)

array([-0.4056669 , -0.25470009, -0.57459267, -0.71994004,  1.14583364])

In [22]:
np.random.randn(6,7)

array([[-0.32023514,  0.10903795, -0.1920224 , -1.02110714, -1.24068953,
         1.19621754,  0.56701339],
       [-0.1775355 , -0.48155609,  0.28657106, -0.25653648, -0.37336037,
        -0.81357008,  0.17284519],
       [ 0.03443988,  0.63621053, -0.84650913,  0.98670753,  1.53390189,
         1.0400971 , -2.13206866],
       [-1.94662917, -1.65102432,  0.67087062, -1.1742971 , -0.5792436 ,
        -1.20867399,  1.51703675],
       [ 0.70139081, -0.46961369,  0.26098501, -0.53386674,  1.4284399 ,
         0.46170021, -0.93840773],
       [ 0.36379667, -0.96108596,  1.34221899,  0.11605397, -0.00259984,
        -2.08165585,  0.45869413]])

In [23]:
#randint

In [36]:
np.random.randint(1,100)  #1 is inclusive but 100 is exclusive

83

In [78]:
np.random.randint(101,136,23)

array([120, 113, 118, 109, 117, 106, 133, 129, 129, 116, 133, 114, 118,
       111, 126, 132, 116, 115, 130, 128, 121, 118, 112])

### seed

* set random state so that same 'random' results can be produced over and over again

In [80]:
np.random.seed(137)  #random_state
np.random.randint(101,138,43)

array([131, 114, 120, 112, 115, 102, 123, 124, 109, 129, 124, 129, 132,
       113, 107, 116, 107, 113, 113, 117, 131, 128, 132, 108, 134, 130,
       113, 115, 110, 116, 118, 120, 103, 110, 137, 131, 103, 125, 136,
       129, 104, 134, 127])

In [83]:
np.random.seed(137)  #random_state
np.random.randn(10,3)

array([[ 1.09077549,  1.06558071,  4.51574031],
       [-0.66767452, -0.40789271,  0.9866497 ],
       [ 0.80106522,  1.02688747,  0.0328846 ],
       [ 1.1345712 ,  0.29244141, -0.80623546],
       [ 0.12572281,  1.02150418,  1.27691408],
       [-0.10868027, -1.63155944,  0.21149633],
       [ 0.49139659,  2.01746651,  1.38351189],
       [-1.27071272,  0.20827071,  0.21601028],
       [ 1.4714186 ,  0.38730203, -1.77436628],
       [ 0.59428484, -1.10337818, -0.5370898 ]])

### Array Attributes and Methods

In [84]:
#arange
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
ranar = np.random.randint(0,50,12)
ranar

array([ 8, 27, 11, 34, 12, 29, 49, 36, 41, 39, 49, 31])

In [86]:
#reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
ranar.reshape(4,3)

array([[ 8, 27, 11],
       [34, 12, 29],
       [49, 36, 41],
       [39, 49, 31]])

In [89]:
#max
ranar.max()

49

In [90]:
#argmax
ranar.argmax()

6

In [91]:
#min
ranar.min()

8

In [92]:
#argmin
ranar.argmin()

0

In [93]:
#Shape: is an attribute. Means it does not take in any parameter

arr.shape

(25,)

In [100]:
arr1 = arr.reshape(25,1)
arr1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [97]:
arr1.shape

(25, 1)

In [98]:
#dtype
arr.dtype

dtype('int64')