In [1]:
import numpy as np

In [5]:
#create array
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
#Bracket Indexing and Selection
arr[9]

18

In [7]:
arr[2:6]

array([ 4,  6,  8, 10])

### Broadcasting

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [11]:
#reset array
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
slice_of_array = arr[0:6]
slice_of_array

array([ 0,  2,  4,  6,  8, 10])

In [13]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18, 20])

* Data is not copied. When we assigned to variable 'slice_of_array', it was just a view of original array. This helps in avoiding memory problem. 

In [15]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18, 20])

In [21]:
lst = [1,2,3,4,5,6]
LST1 = lst[1:3]

In [22]:
LST1 

[2, 3]

In [18]:
LST1[0] = 100

In [19]:
LST1

[100, 3]

In [20]:
lst

[1, 2, 3, 4, 5, 6]

### Indexing a 2D array

In [26]:
arr_2d = np.array(([2,4,6],[12,16,18],[32,38,44]))
arr_2d

array([[ 2,  4,  6],
       [12, 16, 18],
       [32, 38, 44]])

In [27]:
arr_2d[1]

array([12, 16, 18])

In [28]:
arr_2d[1][-1]

18

In [29]:
arr_2d[2][-2]

38

In [30]:
arr_2d[-2,1]

16

In [32]:
arr_2d[:,:]

array([[ 2,  4,  6],
       [12, 16, 18],
       [32, 38, 44]])

In [33]:
arr_2d[:,1]

array([ 4, 16, 38])

In [34]:
arr_2d[1:,1:]

array([[16, 18],
       [38, 44]])

In [35]:
arr_2d[:-1,:-1]

array([[ 2,  4],
       [12, 16]])

In [36]:
arr_2d[:2,:2]

array([[ 2,  4],
       [12, 16]])

## Conditional Selection

In [37]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])