In [1]:
import numpy as np

In [2]:
#create array
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
arr+arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [4]:
arr*arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [5]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2617/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
1/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2617/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 0.5       , 0.25      , 0.16666667, 0.125     ,
       0.1       , 0.08333333, 0.07142857, 0.0625    , 0.05555556,
       0.05      ])

In [8]:
arr**3

array([   0,    8,   64,  216,  512, 1000, 1728, 2744, 4096, 5832, 8000])

## Universal Array Functions

In [9]:
np.sqrt(arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595])

In [10]:
np.exp(arr)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07, 4.85165195e+08])

In [18]:
np.log(arr)

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2617/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227])

In [11]:
np.sin(arr)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525])

In [12]:
arr.sum()

110

In [13]:
arr.mean()

10.0

In [14]:
arr.max()

20

## Axis Logic

In [15]:
arr_2d = np.array(([2,4,6],[12,16,18],[32,38,44]))
arr_2d

array([[ 2,  4,  6],
       [12, 16, 18],
       [32, 38, 44]])

In [16]:
#axis=0 along vertical axis
arr_2d.sum(axis = 0)

array([46, 58, 68])

In [17]:
#axis=1 along horizontal axis
arr_2d.sum(axis=1)

array([ 12,  46, 114])